[tool.black]
line-length = 100
target-version = ["py313"]

[tool.ruff]
line-length = 100
select = ["E","F","I","UP"]
ignore = ["E203","E266","E402","E501"]
exclude = [".git",".venv",".mypy_cache",".ruff_cache","build","dist"]

[tool.nbqa.config]
addopts = {black = "--line-length=100"}

[tool.mypy]
python_version = "3.13"
ignore_missing_imports = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
