[tool.ruff]
line-length = 140
target-version = "py39"

[tool.ruff.lint]
select = ["E","F","I"]
ignore = [
  "E402", # imports not at top (notebook pattern)
  "E501", # line too long
  "I001", # import sort in notebooks/extracted scripts
]

[tool.flake8]
max-line-length = 220
extend-ignore = "E402,E302,E305,E231,E221,E301,E303,E225,E128,W391"
