name: CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          ref: ${{ github.head_ref || github.ref_name }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black nbqa mypy
      - name: Auto-fix with Ruff
        run: |
          ruff check --fix . || true
          nbqa ruff --fix . || true
      - name: Auto-format with Black
        run: |
          black .
          nbqa black .
      - name: Commit auto-fixes (if any)
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "ci: apply auto-fixes (ruff/black/nbqa)"
            git push origin HEAD:${BRANCH_NAME}
          else
            echo "No changes to commit."
          fi
      - name: Ruff (verify clean)
        run: |
          ruff check .
          nbqa ruff .
      - name: Black (verify clean)
        run: |
          black --check .
          nbqa black --check .
      - name: mypy (loose)
        run: |
          mypy --exclude 'datasets|.github|scripts' . || true
      - name: Notebook syntax check
        run: |
          python scripts/check_notebooks.py
