name: CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black nbqa mypy
      - name: Ruff (Python) lint
        run: |
          ruff check .
      - name: Black (check)
        run: |
          black --check .
      - name: nbQA Black (notebooks)
        run: |
          nbqa black --check .
      - name: nbQA Ruff (notebooks)
        run: |
          nbqa ruff --select E,F .
      - name: mypy (loose)
        run: |
          mypy --exclude 'datasets|.github|scripts' . || true
      - name: Notebook syntax check
        run: |
          python scripts/check_notebooks.py
