name: CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          ref: ${{ github.head_ref || github.ref_name }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install "ruff>=0.5,<0.6" "black>=24.3,<25" "nbqa>=1.9,<2" "mypy>=1.10,<2"
      - name: Auto-fix with Ruff
        run: |
          ruff check --fix . || true
          nbqa ruff --fix . || true
      - name: Auto-format with Black
        run: |
          black .
          nbqa black .
      - name: Detect changes
        id: changes
        run: |
          if ! git diff --quiet; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi
          status=$(git status --short || true)
          if printf '%s\n' "$status" | grep -E '^.. \\.github/workflows/' >/dev/null; then
            echo "workflow_changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "workflow_changed=false" >> "$GITHUB_OUTPUT"
          fi
          if printf '%s\n' "$status" | grep -E -v '^.. \\.github/workflows/' | grep -q '[^[:space:]]'; then
            echo "non_workflow_changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "non_workflow_changed=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Commit auto-fixes back to branch (push events, non-main)
        if: steps.changes.outputs.changed == 'true' && steps.changes.outputs.non_workflow_changed == 'true' && steps.changes.outputs.workflow_changed != 'true' && github.event_name == 'push' && github.ref != 'refs/heads/main'
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git reset HEAD -- .github/workflows || true
          if git diff --cached --quiet; then
            echo "No non-workflow changes to commit after exclusions."
            exit 0
          fi
          git commit -m "ci: apply auto-fixes (ruff/black/nbqa)"
          git push origin HEAD:${BRANCH_NAME}
      - name: Create PR with autofixes (pull_request events)
        if: steps.changes.outputs.changed == 'true' && steps.changes.outputs.non_workflow_changed == 'true' && steps.changes.outputs.workflow_changed != 'true' && github.event_name == 'pull_request'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ github.base_ref }}
          branch: autofix/pr-${{ github.event.pull_request.number }}
          title: "ci: apply auto-fixes for PR #${{ github.event.pull_request.number }}"
          body: |
            This automated PR applies formatting and lint fixes to the code in PR #${{ github.event.pull_request.number }}.
            Generated by CI after running Ruff/Black/NBQA.
          labels: autofix
          commit-message: "ci: apply auto-fixes (ruff/black/nbqa)"
          add-paths: |
            .
            :!**/.github/workflows/**
      - name: Create PR with autofixes (push to main)
        if: steps.changes.outputs.changed == 'true' && steps.changes.outputs.non_workflow_changed == 'true' && steps.changes.outputs.workflow_changed != 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: autofix/main-${{ github.run_id }}
          title: "ci: apply auto-fixes for main"
          body: |
            This automated PR applies formatting and lint fixes to main.
            Generated by CI after running Ruff/Black/NBQA.
          labels: autofix
          commit-message: "ci: apply auto-fixes (ruff/black/nbqa)"
          add-paths: |
            .
            :!**/.github/workflows/**
      - name: Ruff (verify clean)
        run: |
          ruff check .
          nbqa ruff .
      - name: Black (verify clean)
        run: |
          black --check .
          nbqa black --check .
      - name: mypy (loose)
        run: |
          mypy --exclude 'datasets|.github|scripts' . || true
      - name: Notebook syntax check
        run: |
          python scripts/check_notebooks.py
