name: CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black nbqa mypy
      - name: Auto-fix with Ruff
        run: |
          ruff check --fix . || true
          nbqa ruff --fix . || true
      - name: Auto-format with Black
        run: |
          black .
          nbqa black .
      - name: Ruff (verify clean)
        run: |
          ruff check .
          nbqa ruff .
      - name: Black (verify clean)
        run: |
          black --check .
          nbqa black --check .
      - name: mypy (loose)
        run: |
          mypy --exclude 'datasets|.github|scripts' . || true
      - name: Notebook syntax check
        run: |
          python scripts/check_notebooks.py
