name: Label PRs for AutoMerge
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  add-automerge-label:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Ensure 'automerge' label exists
        uses: peter-evans/create-or-update-labels@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            [
              {
                "name": "automerge",
                "color": "0E8A16",
                "description": "Enable auto-merge via workflow"
              }
            ]
      - name: Add 'automerge' label to PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            automerge
