name: PR on Push
on:
  push:
    branches-ignore:
      - main
      - 'autofix/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Create or update PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref_name }}
          title: "Auto PR: ${{ github.ref_name }}"
          body: |
            Automated PR created by GitHub Actions on push to branch `${{ github.ref_name }}`.
            This PR was generated after lint and checks.
          draft: false
